### ISSUE TITLE
[name].tmpl.html fails to compile

### ISSUE THREAD

**Issue by mkazlauskas** [pitr/angular-rails-templates#12]
A template named `[anything].tmpl.html` throws compilation error. Used to work in 0.0.2
